# Generated by Django 3.1.4 on 2020-12-21 11:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator('Invalid Email')], verbose_name='Email address'),
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(10, 'Address is too short')], verbose_name='Address')),
                ('pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{2}\\s{0,1}[0-9]{3}$', 'Invalid Pin Number')], verbose_name='Postal Code')),
                ('city', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Invalid city name')], verbose_name='City')),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Karnataka', 'Karnataka')], default='Kerala', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
